### ISSUE TITLE
Can`t install osrm 

### ISSUE THREAD

**Issue by GelmanDan** [ustroetz/python-osrm#27]
C:\Users\Админ> pip  install osrm
Requirement already satisfied: osrm in c:\python27\lib\site-packages\osrm-0.11.1-py2.7.egg (0.11.1)
Collecting polyline (from osrm)
  Using cached https://files.pythonhosted.org/packages/c1/d0/58a19ca3fbe880145d200518fcd97d176cae07b9677db330f4881954d5f5/polyline-1.3.2-py2.py3-none-any.whl
Collecting GDAL (from osrm)
  Using cached https://files.pythonhosted.org/packages/e5/57/7f0536cd46bebb30e709b8cd3bcebf9c3d4acc4ad5e9d7bfc73cd39c09a9/GDAL-2.3.2.tar.gz
Requirement already satisfied: numpy in c:\python27\lib\site-packages (from osrm) (1.15.3)
Requirement already satisfied: pandas in c:\python27\lib\site-packages (from osrm) (0.23.4)
Collecting shapely (from osrm)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\7272~1\appdata\local\temp\pip-install-o2lqmz\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\python27\lib\ctypes\__init__.py", line 366, in __init__
        self._handle = _dlopen(self._name, mode)
    WindowsError: [Error 126]

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\7272~1\appdata\local\temp\pip-install-o2lqmz\shapely\

try to install osrm module, and have this error.
Do you have solution for this?

**Comment by mthh** [comment]
Not really a solution, but this package depends on a few other python packages such as gdal and shapely.

It seems to fail when installing `shapely`, so what I suggest is to download the shapely wheel (and also the gdal wheel if it's not already installed) adapted to your version of python on [Christoph Gohlke website](https://www.lfd.uci.edu/~gohlke/pythonlibs/) : https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely
After that I suggest you try again to install osrm python package with pip.
